name: CI
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ dev ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: jfgarcia268/vlocity_sfdx:v7.0
    steps:  
    - uses: actions/checkout@v2
    - name: SF deploy	    
      run: |
        echo ${{ secrets.SuperSecret }}  > env.sfdx
        sfdx force:auth:sfdxurl:store -d -a ALIAS -f env.sfdx
        sfdx force:source:deploy --sourcepath salesforce_sfdx --targetusername ALIAS --verbose    
    - name: Vlocity deploy   
      run: |
        echo ${{ secrets.SuperSecret }} > env.sfdx
        sfdx force:auth:sfdxurl:store -d -a ALIAS -f env.sfdx
        vlocity -sfdx.username ALIAS -job Deploy_Delta.yaml packDeploy --verbose true --simpleLogging true  
