name: CI
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
jobs:
  deployCI:
    runs-on: ubuntu-latest
    container:
      image: jfgarcia268/vlocity_sfdx:v7.0
    steps:  
    - uses: actions/checkout@v2
    - name: Check Tools	    
      run: |
        sfdx force  
        vlocity help     
